### PR TITLE
[Vue] migrate manage-custom-vars model and directive to Vue

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

**This PR requires https://github.com/matomo-org/matomo/pull/19012 to be merged first.**

Changes:
* Migrate manage-custom-vars model and directive to Vue.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by diosmosis** [comment]
@AltamashShaikh pinging in case you didn't see this one.

**Comment by AltamashShaikh** [comment]
@diosmosis Looks good to me, its just I am not to familiar with this plugin
@sgiehl can you have a look once ?

**Comment by diosmosis** [comment]
@sgiehl are you able to take a look at this?

**Review by sgiehl — APPROVED** [review]
Looks good to me.

**Pull request merged**
